/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ScoreEntry = IDL.Record({
  'player' : IDL.Principal,
  'score' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllScoresAscending' : IDL.Func([], [IDL.Vec(ScoreEntry)], ['query']),
  'getAllScoresDescending' : IDL.Func([], [IDL.Vec(ScoreEntry)], ['query']),
  'getScore' : IDL.Func([IDL.Nat], [ScoreEntry], ['query']),
  'recordScore' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ScoreEntry = IDL.Record({
    'player' : IDL.Principal,
    'score' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllScoresAscending' : IDL.Func([], [IDL.Vec(ScoreEntry)], ['query']),
    'getAllScoresDescending' : IDL.Func([], [IDL.Vec(ScoreEntry)], ['query']),
    'getScore' : IDL.Func([IDL.Nat], [ScoreEntry], ['query']),
    'recordScore' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };